name: locostall
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  uuid: ^3.0.6
  shared_preferences: ^2.2.0
  http: ^1.1.0
  camera: ^0.10.5+2
  image_picker: ^1.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  image_card: ^0.0.4
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
